# Generated by Django 4.2.7 on 2025-09-04 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_organization_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid international phone number (e.g., +919876543210)', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid international phone number (e.g., +919876543210)', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
    ]
