# Generated by Django 4.2.7 on 2025-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_organization_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile photo', null=True, upload_to='profile_images/%Y/%m/%d/'),
        ),
    ]
