# Generated by Django 4.2.7 on 2025-09-04 16:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sos_reports', '0002_add_is_demo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosreport',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosreport',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sosreport',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid international phone number (e.g., +919876543210)', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='sosreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('FALSE_ALARM', 'False Alarm')], default='PENDING', max_length=15),
        ),
    ]
