# Generated by Django 4.2.7 on 2025-09-09 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos_reports', '0003_sosreport_verified_at_sosreport_verified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosreport',
            name='ai_analysis_data',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed AI analysis results'),
        ),
        migrations.AddField(
            model_name='sosreport',
            name='ai_fraud_score',
            field=models.FloatField(default=0.0, help_text='AI fraud detection score (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='sosreport',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid international phone number (e.g., +919876543210)', regex='^\\+[1-9]\\d{9,14}$')]),
        ),
    ]
