# Generated by Django 4.1.13 on 2025-09-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos_reports', '0004_sosreport_ai_analysis_data_sosreport_ai_fraud_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmedia',
            name='imagekit_file_id',
            field=models.CharField(blank=True, help_text='ImageKit file ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportmedia',
            name='imagekit_file_type',
            field=models.CharField(blank=True, help_text='MIME type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportmedia',
            name='imagekit_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportmedia',
            name='imagekit_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='reportmedia',
            name='imagekit_url',
            field=models.URLField(blank=True, help_text='ImageKit URL', null=True),
        ),
        migrations.AlterField(
            model_name='reportmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/'),
        ),
    ]
