# Generated by Django 4.1.13 on 2025-09-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos_reports', '0005_reportmedia_imagekit_file_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosreport',
            name='is_demo',
        ),
    ]
