services:
  - type: web
    name: nudrrs-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn nudrrs.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "nudrrs-backend.onrender.com"
      - key: MONGODB_CONNECTION_STRING
        fromService:
          name: nudrrs-mongodb
          property: connectionString
    plan: free

  - type: web
    name: nudrrs-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://nudrrs-backend.onrender.com"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    plan: free

databases:
  - name: nudrrs-mongodb
    databaseName: NUDDRS
    user: NUDDRS
    plan: free
    mongoDBVersion: "6.0"