# Generated by Django 4.2.7 on 2025-09-04 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_type', models.CharField(choices=[('police', 'Police'), ('fire', 'Fire Department'), ('medical', 'Medical Emergency'), ('disaster', 'Disaster Management'), ('rescue', 'Rescue Services'), ('shelter', 'Shelter'), ('food', 'Food Relief'), ('other', 'Other')], max_length=20)),
                ('phone_number', models.CharField(max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_area', models.CharField(blank=True, max_length=200)),
                ('is_24_7', models.BooleanField(default=False)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('languages_supported', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'db_table': 'chatbot_emergency_contacts',
                'ordering': ['contact_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('medical', 'Medical Emergency'), ('evacuation', 'Evacuation'), ('shelter', 'Shelter'), ('food', 'Food & Water'), ('communication', 'Communication'), ('safety', 'Safety Tips'), ('contacts', 'Emergency Contacts')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency FAQ',
                'verbose_name_plural': 'Emergency FAQs',
                'db_table': 'emergency_faqs',
                'ordering': ['-priority', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'chat_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('system', 'System Message')], max_length=10)),
                ('content', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('user_messages', models.PositiveIntegerField(default=0)),
                ('bot_messages', models.PositiveIntegerField(default=0)),
                ('top_intents', models.JSONField(blank=True, default=dict)),
                ('resolved_queries', models.PositiveIntegerField(default=0)),
                ('escalated_queries', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.FloatField(blank=True, null=True)),
                ('user_satisfaction', models.IntegerField(blank=True, null=True)),
                ('session_duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chatbot Analytics',
                'verbose_name_plural': 'Chatbot Analytics',
                'db_table': 'chatbot_analytics',
                'ordering': ['-created_at'],
            },
        ),
    ]
