# Generated by Django 4.2.7 on 2025-09-04 12:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('fire_truck', 'Fire Truck'), ('rescue_team', 'Rescue Team'), ('medical_team', 'Medical Team'), ('food_supply', 'Food Supply'), ('water_supply', 'Water Supply'), ('shelter', 'Shelter'), ('evacuation_vehicle', 'Evacuation Vehicle'), ('communication_equipment', 'Communication Equipment'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('available_capacity', models.PositiveIntegerField(default=1)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=17)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Resource',
                'verbose_name_plural': 'Emergency Resources',
                'db_table': 'emergency_resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('medical', 'Medical Emergency'), ('rescue', 'Rescue Required'), ('shelter', 'Shelter Needed'), ('food', 'Food/Water Required'), ('evacuation', 'Evacuation Required'), ('fire', 'Fire Emergency'), ('flood', 'Flood Emergency'), ('earthquake', 'Earthquake Emergency'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='pending', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=17)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('ai_verified', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_category', models.CharField(blank=True, choices=[('medical', 'Medical Emergency'), ('rescue', 'Rescue Required'), ('shelter', 'Shelter Needed'), ('food', 'Food/Water Required'), ('evacuation', 'Evacuation Required'), ('fire', 'Fire Emergency'), ('flood', 'Flood Emergency'), ('earthquake', 'Earthquake Emergency'), ('other', 'Other')], max_length=20)),
                ('ai_notes', models.TextField(blank=True)),
                ('response_notes', models.TextField(blank=True)),
                ('estimated_resolution_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'responder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Report',
                'verbose_name_plural': 'SOS Reports',
                'db_table': 'sos_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='sos_reports.sosreport')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Update',
                'verbose_name_plural': 'Report Updates',
                'db_table': 'report_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sos_reports.sosreport')),
            ],
            options={
                'verbose_name': 'Report Comment',
                'verbose_name_plural': 'Report Comments',
                'db_table': 'report_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
